# Dependency Resolution (https://pnpm.io/settings/dependency-resolution)
update:
  githubActions: true
minimumReleaseAge: 1440 # 1 day in minutes
minimumReleaseAgeStrict: true
trustPolicy: no-downgrade
blockExoticSubdeps: true

# Build settings (https://pnpm.io/settings/build)
verifyDepsBeforeRun: install
strictDepBuilds: true
allowBuilds:
  lefthook: true

# Other settings (https://pnpm.io/settings/other)
shellEmulator: true

gitChecks: false
